name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIGNING_ALIAS: ${{ vars.SIGNING_ALIAS }}
      SIGNING_STORE_PASS: ${{ vars.SIGNING_STORE_PASS }}
      SIGNING_KEY_PASS: ${{ vars.SIGNING_KEY_PASS }}
      SIGNING_KEY_PATH: ${{ vars.SIGNING_KEY_PATH }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.4'
      - run: gradle clean assembleDebug assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: DNS-debug
          path: app/build/outputs/apk/debug/*.apk
      - uses: actions/upload-artifact@v4
        with:
          name: DNS-release
          path: app/build/outputs/apk/release/*.apk
